import type {
  Employee,
  AttendanceRecord,
  LeaveRequest,
  SmartLeaveAnalysis,
  PayrollRecord,
  Holiday,
  NeedsAttentionAlerts,
  User,
} from '../types';
import { buildSalaryInfo } from '../utils/salaryCalculator';

export const MOCK_USERS: Record<string, User> = {
  employee: {
    id: 'emp-001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@dayflow.io',
    loginId: 'OIRASH20220001',
    role: 'EMPLOYEE',
    employeeId: 'OIRASH20220001',
    companyName: 'Dayflow Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
  },
  hr: {
    id: 'emp-002',
    name: 'Priya Patel',
    email: 'priya.patel@dayflow.io',
    loginId: 'OIPRPA20210002',
    role: 'HR',
    employeeId: 'OIPRPA20210002',
    companyName: 'Dayflow Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
  },
  admin: {
    id: 'emp-003',
    name: 'Vikramaditya Roy',
    email: 'admin@dayflow.io',
    loginId: 'OIVIROY20200000',
    role: 'ADMIN',
    employeeId: 'OIVIROY20200000',
    companyName: 'Dayflow Technologies',
    companyLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'OIRASH20220001',
    employeeCode: 'OIRASH20220001',
    loginId: 'OIRASH20220001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@dayflow.io',
    phone: '+91 98765 43210',
    designation: 'Software Engineer',
    department: 'Engineering',
    manager: 'Vikramaditya Roy',
    location: 'Bengaluru, India',
    company: 'Dayflow Technologies',
    status: 'PRESENT',
    dateOfJoining: '2022-03-15',
    dob: '1992-08-14',
    address: '42, 4th Main, Indiranagar, Bengaluru, Karnataka 560038',
    nationality: 'Indian',
    personalEmail: 'rahul.sharma.personal@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountNumber: '50100234981723',
      ifscCode: 'HDFC0000240',
    },
    securityDetails: {
      panNumber: 'ABCPS1234F',
      uanNumber: '100982341122',
      employeeCode: 'OIRASH20220001',
    },
    salaryInfo: buildSalaryInfo(50000),
    resumeSummary: {
      bio: 'Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem ipsum has been the industry standard dummy text ever since the 1500s.',
      skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'Python'],
      whatILoveAboutMyJob: 'Solving complex engineering workflows, building reliable SaaS systems, and collaborating across high-impact teams.',
      interestsAndHobbies: 'Playing chess, marathon running, open-source contributing, and listening to classical music.',
      certifications: ['AWS Certified Solutions Architect', 'Professional Scrum Master I'],
      experience: [
        { title: 'Software Engineer', company: 'Dayflow Technologies', duration: '2022 - Present' },
        { title: 'Junior Developer', company: 'TechCorp Solutions', duration: '2020 - 2022' },
      ],
      education: [
        { degree: 'B.Tech in Computer Science', institution: 'IIT Bombay', year: '2020' },
      ],
    },
  },
  {
    id: 'OIPRPA20210002',
    employeeCode: 'OIPRPA20210002',
    loginId: 'OIPRPA20210002',
    name: 'Priya Patel',
    email: 'priya.patel@dayflow.io',
    phone: '+91 98123 45678',
    designation: 'HR Officer',
    department: 'Human Resources',
    manager: 'Vikramaditya Roy',
    location: 'Mumbai, India',
    company: 'Dayflow Technologies',
    status: 'PRESENT',
    dateOfJoining: '2021-06-01',
    dob: '1990-11-22',
    address: '102, Silver Oaks, Bandra West, Mumbai 400050',
    nationality: 'Indian',
    personalEmail: 'priya.patel.hr@gmail.com',
    gender: 'Female',
    maritalStatus: 'Married',
    bankDetails: {
      bankName: 'ICICI Bank',
      accountNumber: '001205098765',
      ifscCode: 'ICIC0000012',
    },
    securityDetails: {
      panNumber: 'BCDPP5678K',
      uanNumber: '100789012345',
      employeeCode: 'OIPRPA20210002',
    },
    salaryInfo: buildSalaryInfo(60000),
    resumeSummary: {
      bio: 'HR Specialist specializing in talent acquisition, employee experience, policy compliance, and culture building.',
      skills: ['Talent Acquisition', 'HR Operations', 'Compliance', 'Performance Management'],
      whatILoveAboutMyJob: 'Empowering employees, shaping organizational culture, and creating seamless HR processes.',
      interestsAndHobbies: 'Reading books, travelling, yoga, and blogging.',
      certifications: ['SHRM Certified Professional', 'HR Analytics Certification'],
      experience: [
        { title: 'HR Officer', company: 'Dayflow Technologies', duration: '2021 - Present' },
      ],
      education: [
        { degree: 'MBA in Human Resources', institution: 'XLRI Jamshedpur', year: '2021' },
      ],
    },
  },
  {
    id: 'OIAMVE20230003',
    employeeCode: 'OIAMVE20230003',
    loginId: 'OIAMVE20230003',
    name: 'Aman Verma',
    email: 'aman.verma@dayflow.io',
    phone: '+91 97654 32109',
    designation: 'Senior Backend Engineer',
    department: 'Engineering',
    manager: 'Rahul Sharma',
    location: 'Bengaluru, India',
    company: 'Dayflow Technologies',
    status: 'ON_LEAVE',
    dateOfJoining: '2023-01-10',
    dob: '1995-04-05',
    address: '15, Koramangala 5th Block, Bengaluru 560095',
    nationality: 'Indian',
    personalEmail: 'aman.verma.dev@gmail.com',
    gender: 'Male',
    maritalStatus: 'Single',
    bankDetails: {
      bankName: 'Axis Bank',
      accountNumber: '9180200345671',
      ifscCode: 'UTIB0000123',
    },
    securityDetails: {
      panNumber: 'CDEPA9012M',
      uanNumber: '100456123987',
      employeeCode: 'OIAMVE20230003',
    },
    salaryInfo: buildSalaryInfo(70000),
    resumeSummary: {
      bio: 'Distributed backend developer building scalable microservices, API gateways, and cloud infrastructure.',
      skills: ['Go', 'Node.js', 'PostgreSQL', 'Redis', 'Docker'],
      whatILoveAboutMyJob: 'Building high throughput backend microservices that handle millions of requests seamlessly.',
      interestsAndHobbies: 'Competitive coding, cycling, and photography.',
      certifications: ['Certified Kubernetes Application Developer'],
      experience: [
        { title: 'Senior Backend Engineer', company: 'Dayflow Technologies', duration: '2023 - Present' },
      ],
      education: [
        { degree: 'B.E. in Information Technology', institution: 'PES University', year: '2022' },
      ],
    },
  },
  {
    id: 'OIANRO20220004',
    employeeCode: 'OIANRO20220004',
    loginId: 'OIANRO20220004',
    name: 'Ananya Roy',
    email: 'ananya.roy@dayflow.io',
    phone: '+91 99887 76655',
    designation: 'Product Designer',
    department: 'Design',
    manager: 'Rahul Sharma',
    location: 'Delhi NCR, India',
    company: 'Dayflow Technologies',
    status: 'PRESENT',
    dateOfJoining: '2022-09-01',
    dob: '1994-03-18',
    address: '88, DLF Phase 4, Gurugram, Haryana 122002',
    nationality: 'Indian',
    personalEmail: 'ananya.roy.design@gmail.com',
    gender: 'Female',
    maritalStatus: 'Single',
    bankDetails: {
      bankName: 'State Bank of India',
      accountNumber: '30987654321',
      ifscCode: 'SBIN0001234',
    },
    securityDetails: {
      panNumber: 'EFGAR3456N',
      uanNumber: '100345678901',
      employeeCode: 'OIANRO20220004',
    },
    salaryInfo: buildSalaryInfo(55000),
    resumeSummary: {
      bio: 'UI/UX product designer creating accessible, beautiful SaaS component systems.',
      skills: ['Figma', 'UI/UX Design', 'Design Systems', 'Tailwind CSS'],
      whatILoveAboutMyJob: 'Turning complex workflows into simple, elegant visual experiences.',
      interestsAndHobbies: 'UI prototyping, digital painting, and cafe hopping.',
      certifications: ['Google UX Design Professional Certificate'],
      experience: [
        { title: 'Product Designer', company: 'Dayflow Technologies', duration: '2022 - Present' },
      ],
      education: [
        { degree: 'B.Des in Communication Design', institution: 'NID Ahmedabad', year: '2022' },
      ],
    },
  },
  {
    id: 'OIVI SI20230005',
    employeeCode: 'OIVI SI20230005',
    loginId: 'OIVI SI20230005',
    name: 'Vikram Singh',
    email: 'vikram.singh@dayflow.io',
    phone: '+91 96543 21098',
    designation: 'DevOps Engineer',
    department: 'Engineering',
    manager: 'Rahul Sharma',
    location: 'Hyderabad, India',
    company: 'Dayflow Technologies',
    status: 'ABSENT',
    dateOfJoining: '2023-04-15',
    dob: '1993-07-29',
    address: '77, HITEC City, Hyderabad, Telangana 500081',
    nationality: 'Indian',
    personalEmail: 'vikram.singh.devops@gmail.com',
    gender: 'Male',
    maritalStatus: 'Married',
    bankDetails: {
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '7812903456',
      ifscCode: 'KKBK0000456',
    },
    securityDetails: {
      panNumber: 'GHIVS7890P',
      uanNumber: '100654987321',
      employeeCode: 'OIVI SI20230005',
    },
    salaryInfo: buildSalaryInfo(65000),
    resumeSummary: {
      bio: 'Cloud engineer automating infrastructure, Kubernetes orchestration, and CI/CD pipelines.',
      skills: ['Kubernetes', 'Terraform', 'Docker', 'AWS', 'CI/CD'],
      whatILoveAboutMyJob: 'Ensuring zero downtime and building self-healing infrastructure pipelines.',
      interestsAndHobbies: 'Gaming, home automation, and trekking.',
      certifications: ['AWS Certified DevOps Engineer - Professional'],
      experience: [
        { title: 'DevOps Engineer', company: 'Dayflow Technologies', duration: '2023 - Present' },
      ],
      education: [
        { degree: 'B.Tech in IT', institution: 'NIT Warangal', year: '2021' },
      ],
    },
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-01',
    employeeId: 'OIRASH20220001',
    employeeName: 'Rahul Sharma',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:05 AM',
    checkOut: null,
    workHours: 7.2,
    extraHours: 1.5,
    status: 'PRESENT',
  },
  {
    id: 'att-02',
    employeeId: 'OIPRPA20210002',
    employeeName: 'Priya Patel',
    department: 'Human Resources',
    date: '2026-08-22',
    checkIn: '09:00 AM',
    checkOut: null,
    workHours: 7.3,
    extraHours: 0.0,
    status: 'PRESENT',
  },
  {
    id: 'att-03',
    employeeId: 'OIAMVE20230003',
    employeeName: 'Aman Verma',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    workHours: 0.0,
    extraHours: 0.0,
    status: 'ON_LEAVE',
  },
  {
    id: 'att-04',
    employeeId: 'OIANRO20220004',
    employeeName: 'Ananya Roy',
    department: 'Design',
    date: '2026-08-22',
    checkIn: '09:15 AM',
    checkOut: null,
    workHours: 7.0,
    extraHours: 0.5,
    status: 'PRESENT',
  },
  {
    id: 'att-05',
    employeeId: 'OIVI SI20230005',
    employeeName: 'Vikram Singh',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: null,
    checkOut: null,
    workHours: 0.0,
    extraHours: 0.0,
    status: 'ABSENT',
  },
];

export const INITIAL_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'lr-001',
    employeeId: 'OIRASH20220001',
    employeeName: 'Rahul Sharma',
    department: 'Engineering',
    type: 'Paid Time Off',
    startDate: '2026-08-25',
    endDate: '2026-08-27',
    allocationDays: 3,
    status: 'PENDING',
    reason: 'Annual family trip to Goa.',
    createdAt: '2026-08-20',
  },
  {
    id: 'lr-002',
    employeeId: 'OIAMVE20230003',
    employeeName: 'Aman Verma',
    department: 'Engineering',
    type: 'Sick Time Off',
    startDate: '2026-08-25',
    endDate: '2026-08-26',
    allocationDays: 2,
    status: 'PENDING',
    reason: 'Recovery from acute flu.',
    attachmentUrl: 'medical_certificate_aman.pdf',
    hasMedicalGuidance: true,
    createdAt: '2026-08-21',
  },
  {
    id: 'lr-003',
    employeeId: 'OIVI SI20230005',
    employeeName: 'Vikram Singh',
    department: 'Engineering',
    type: 'Casual Leave',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    allocationDays: 3,
    status: 'PENDING',
    reason: 'Personal home renovation.',
    createdAt: '2026-08-19',
  },
];

export const SMART_LEAVE_ANALYSIS_DATA: Record<string, SmartLeaveAnalysis> = {
  'lr-001': {
    leaveRequestId: 'lr-001',
    employeeName: 'Rahul Sharma',
    leaveDates: '25 Aug → 27 Aug 2026',
    type: 'Paid Time Off',
    coverageBefore: 90,
    coverageDuring: 68,
    coverageAfter: 90,
    holidayOverlap: [
      { date: '26 Aug 2026', name: 'Janmashtami (Company Holiday)' },
    ],
    effectiveLeaveDays: 2,
    overlappingLeaves: [
      { employeeName: 'Aman Verma', dates: '25–26 Aug', type: 'Sick Time Off' },
      { employeeName: 'Priya Patel', dates: '27 Aug', type: 'Casual Leave' },
    ],
    recommendation: 'APPROVE WITH CAUTION',
    recommendationReason: 'Engineering team coverage falls to 68% during requested window. However, 26 Aug is a company holiday, reducing effective leave days to 2.',
  },
  'lr-002': {
    leaveRequestId: 'lr-002',
    employeeName: 'Aman Verma',
    leaveDates: '25 Aug → 26 Aug 2026',
    type: 'Sick Time Off',
    coverageBefore: 90,
    coverageDuring: 72,
    coverageAfter: 90,
    holidayOverlap: [
      { date: '26 Aug 2026', name: 'Janmashtami (Company Holiday)' },
    ],
    effectiveLeaveDays: 1,
    overlappingLeaves: [
      { employeeName: 'Rahul Sharma', dates: '25–27 Aug', type: 'Paid Time Off' },
    ],
    recommendation: 'APPROVE WITH CAUTION',
    recommendationReason: 'Sick leave requests are treated with high priority. Medical certificate uploaded. Coverage impact is mild (72%).',
  },
  'lr-003': {
    leaveRequestId: 'lr-003',
    employeeName: 'Vikram Singh',
    leaveDates: '28 Aug → 30 Aug 2026',
    type: 'Casual Leave',
    coverageBefore: 88,
    coverageDuring: 45,
    coverageAfter: 88,
    holidayOverlap: [],
    effectiveLeaveDays: 3,
    overlappingLeaves: [
      { employeeName: 'Aman Verma', dates: '28–29 Aug', type: 'Paid Time Off' },
    ],
    recommendation: 'REJECT',
    recommendationReason: 'Engineering coverage drops to 45%, breaching mandatory compliance threshold of 60%. Multiple key engineers out.',
  },
};

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay-1001',
    employeeId: 'OIRASH20220001',
    employeeName: 'Rahul Sharma',
    designation: 'Software Engineer',
    department: 'Engineering',
    monthYear: 'August 2026',
    baseSalary: 50000,
    overtimeHours: 6.5,
    overtimePay: 2400,
    unpaidLeaveDays: 0,
    unpaidLeaveDeduction: 0,
    netPayable: 52400,
    status: 'PROCESSED',
  },
  {
    id: 'pay-1002',
    employeeId: 'OIPRPA20210002',
    employeeName: 'Priya Patel',
    designation: 'HR Officer',
    department: 'Human Resources',
    monthYear: 'August 2026',
    baseSalary: 60000,
    overtimeHours: 0.0,
    overtimePay: 0,
    unpaidLeaveDays: 0,
    unpaidLeaveDeduction: 0,
    netPayable: 60000,
    status: 'PROCESSED',
  },
  {
    id: 'pay-1003',
    employeeId: 'OIAMVE20230003',
    employeeName: 'Aman Verma',
    designation: 'Senior Backend Engineer',
    department: 'Engineering',
    monthYear: 'August 2026',
    baseSalary: 70000,
    overtimeHours: 0.0,
    overtimePay: 0,
    unpaidLeaveDays: 1,
    unpaidLeaveDeduction: 2333,
    netPayable: 67667,
    status: 'DRAFT',
  },
];

export const UPCOMING_HOLIDAYS: Holiday[] = [
  { id: 'hol-1', name: 'Independence Day', date: '2026-08-15', day: 'Saturday' },
  { id: 'hol-2', name: 'Janmashtami', date: '2026-08-26', day: 'Wednesday' },
  { id: 'hol-3', name: 'Ganesh Chaturthi', date: '2026-09-14', day: 'Monday' },
  { id: 'hol-4', name: 'Gandhi Jayanti', date: '2026-10-02', day: 'Friday' },
  { id: 'hol-5', name: 'Diwali (Deepavali)', date: '2026-11-08', day: 'Sunday' },
  { id: 'hol-6', name: 'Christmas', date: '2026-12-25', day: 'Friday' },
  { id: 'hol-7', name: 'Republic Day', date: '2026-01-26', day: 'Monday' },
  { id: 'hol-8', name: 'Holi', date: '2026-03-14', day: 'Saturday' },
  { id: 'hol-9', name: 'Good Friday', date: '2026-04-03', day: 'Friday' },
  { id: 'hol-10', name: 'Labour Day', date: '2026-05-01', day: 'Friday' },
];

export const INITIAL_NEEDS_ATTENTION: NeedsAttentionAlerts = {
  pendingLeaveCount: 7,
  employeesApproachingOvertime: [
    { employeeName: 'Vikram Singh', hoursThisMonth: 28, maxAllowed: 30 },
    { employeeName: 'Rahul Sharma', hoursThisMonth: 25, maxAllowed: 30 },
    { employeeName: 'Ananya Roy', hoursThisMonth: 24, maxAllowed: 30 },
  ],
  payrollChangePercentage: +6.2,
};
