"""add attendance extra_hours

Revision ID: 531a5d356189
Revises: e195dfff9156
Create Date: 2026-08-22 10:43:31.184670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531a5d356189'
down_revision: Union[str, Sequence[str], None] = 'e195dfff9156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('extra_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'extra_hours')
    # ### end Alembic commands ###
